# Choose the ghost version
ARG  CODE_VERSION=3.42.5
FROM ghost:${CODE_VERSION}
LABEL maintainer="gnimmelf"

# Set the working directory.
WORKDIR /var/lib/ghost

RUN ghost config url http://localhost:3102

EXPOSE 2368
