# Choose the ghost version
ARG  CODE_VERSION=latest
FROM ghost:${CODE_VERSION}
LABEL maintainer="gnimmelf"

# Set the working directory.
WORKDIR /var/lib/ghost

RUN ghost config url http://localhost:3102

EXPOSE 2368
